targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          exclude:
            - "**/test/**"
        options:
          ignore_for_file:
            - lines_longer_than_80_chars
            - require_trailing_commas
            - cast_nullable_to_non_nullable
            - unnecessary_null_checks
            - strict_raw_type
            - duplicate_ignore
            - prefer_const_constructors

      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/src/models/**.dart

        options:
          explicit_to_json: true
          include_if_null: true
          any_map: true

      autoequal_gen:
        enabled: true
        options:
          auto_include: true
