name: pnv
description: A package to help with safely storing pnv publicly
version: 0.0.3

environment:
    sdk: '>=3.5.0 <4.0.0'

dependencies:
    args: ^2.5.0
    crypto: ^3.0.3
    file: ^7.0.0
    path: ^1.9.0
    pointycastle: ^3.9.1
    yaml: ^3.1.2

executables:
    pnv:
