name: pnv
version: 1.7.1
description: A package to help with safely storing environment variables publicly
repository: https://github.com/mrgnhnt96/pnv
issue_tracker: https://github.com/mrgnhnt96/pnv/issues
funding:
  - https://github.com/sponsors/mrgnhnt96
topics:
  - env
  - dotenv
  - environment-variables
  - environment

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  args: ^2.5.0
  change_case: ^2.2.0
  crypto: ^3.0.3
  equatable: ^2.0.7
  file: ^7.0.0
  json_annotation: ^4.9.0
  mason_logger: ^0.3.2
  path: ^1.9.0
  pointycastle: ^3.9.1
  yaml: ^3.1.3

dev_dependencies:
  autoequal_gen: ^0.9.1
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  mocktail: ^1.0.4
  test: ^1.25.14

dependency_overrides:
  source_gen: ^2.0.0

executables:
  pnv:
